<!-- 

<?php
    //$countries = $block->getAllowedCountries();
?>
<div id="shipping-quote-wrapper">
    <div id="shipping-quote-content">
        <h3><?= __('Estimate shipping cost') ?></h3>
        <div class="selection-wrapper">
            <select id="country-select">
                <?php /*foreach ($countries as $name => $id): ?>
                    <option value="<?= $id ?>" <?php if ($id == 'IT') echo 'selected'; ?>><?= $name ?></option>
                <?php endforeach;*/ ?>
            </select>
            <a href="#" id="estimator" class="action continue"><span><?= __('Estimate') ?></span></a>
            <div class="clearfix"></div>
        </div>
        <div class="quote-items-wrapper">
            <table id="quote-items">
                <thead>
                    <tr>
                        <th><?= __('Method') ?></th>
                        <th><?= __('Amount') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr data-template="1">
                        <td>#TITOLO#</td>
                        <td>#AMOUNT#</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

-->