<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
?>
<?php $_total = $block->getItems()->getSize() ?>
<?php if ($_total): ?>
    <a style="float:right;" href="#" class="action print" title="<?php /* @escapeNotVerified */
    echo __('Print This Page') ?>">
        <span><?php /* @escapeNotVerified */
            echo __('Print This Page') ?></span>
    </a>
    <style type="text/css">        
        .compare-description-value[data-mage-init] {
            display: none !important;
        }
    </style>
    <script type="text/javascript">
        require(
            ['jquery'],
            function($) {
                var tableComparison = $('.table-wrapper.comparison');
                if (typeof window.compareDone === 'undefined') {
                    window.compareDone = true;
                } else {
                    if (window.compareDone) {
                        tableComparison.trigger('contentUpdated');
                        tableComparison.attr('data-ready', '1');
                        $('.h-scrollbar').width($('#product-comparison').width());
                        if ($('.h-scrollbar').width() > $('.h-scrollbar-wrapper').width()) {
                            $('.h-scrollbar-wrapper').attr('data-ready', '1');
                        } else {
                            $('.h-scrollbar-wrapper').attr('data-ready', '0');
                        }
                        return;
                    }
                }

                tableComparison.before('<div class="h-scrollbar-wrapper" data-ready="0">\
        <div class="h-scrollbar">\
        </div>\
    </div>\
    <style type="text/css">\
        .h-scrollbar-wrapper {\
            height: 20px;\
            overflow-y: hidden;\
            overflow-x: scroll;\
            width: 100%;\
        }\
        .h-scrollbar-wrapper[data-ready="0"] {\
            visibility: hidden;\
        }\
        .h-scrollbar {\
            height: 20px;\
        }\
        .table-wrapper.comparison[data-ready="0"] {\
            visibility: hidden;\
        }\
        .table-comparison .products-grid .item .box-image {\
            height: 270px;\
            width: 270px;\
        }\
        .compare-description-value [data-role="trigger"] span {\
            font-size: 16px;\
            font-weight: bold;\
            margin-right: 30px;\
        }\
        .compare-description-value [data-role="trigger"] span:hover,\
        .compare-description-value [data-role="trigger"] span ~ i:hover {\
            cursor: pointer;\
        }\
        .compare-description-value [data-role="collapsible"][aria-selected="true"] .fa.fa-chevron-down {\
            display: none !important;\
        }\
        .compare-description-value [data-role="collapsible"][aria-selected="false"] .fa.fa-chevron-up {\
            display: none !important;\
        }\
    </style>');

                var scrollbarWrapper = $('.h-scrollbar-wrapper');
                $('.h-scrollbar').width($('#product-comparison').width());

                if ($('.h-scrollbar').width() > $('.h-scrollbar-wrapper').width()) {
                    $('.h-scrollbar-wrapper').attr('data-ready', '1');
                } else {
                    $('.h-scrollbar-wrapper').attr('data-ready', '0');
                }
                
                scrollbarWrapper.scroll(function() {
                    tableComparison.scrollLeft(
                        scrollbarWrapper.scrollLeft()
                    );
                });

                tableComparison.scroll(function() {
                    scrollbarWrapper.scrollLeft(
                        tableComparison.scrollLeft()
                    );
                });

                tableComparison.find('tr[data-attribute-code="sku"]').before(tableComparison.find('tr[data-attribute-code="manufacturer"]'));

                tableComparison.attr('data-ready', '1');
            }
        );
    </script>
    <div class="table-wrapper comparison" data-ready="0">
        <table class="data table table-comparison" id="product-comparison"
               data-mage-init='{"compareList":{
                    "windowPrintSelector":".action.print",
                    "productsInRow":"5",
                    "selectors":{
                        "productAddToCartSelector":"button.action.tocart"}
                }}'>
            <caption class="table-caption"><?php /* @escapeNotVerified */
                echo __('Compare Products') ?></caption>
            <thead>
            <tr>
                <?php $_i = 0 ?>
                <?php foreach ($block->getItems() as $_item): ?>
                    <?php if ($_i++ == 0): ?>
                        <th scope="row" class="cell remove"><span><?php /* @escapeNotVerified */
                                echo __('Remove Product') ?></span></th>
                    <?php endif; ?>


                    <td class="cell remove product">
                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                        <a href="#" data-post='<?php /* @escapeNotVerified */
                        echo $compareHelper->getPostDataRemove($_item); ?>'
                           class="action delete" title="<?php /* @escapeNotVerified */
                        echo __('Remove Product') ?>">
                                <span><?php /* @escapeNotVerified */
                                    //echo __('Remove Product') ?>
                                    <i class="fa fa-remove fa-lg"></i></span>
                        </a>
                    </td>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tbody>
            <tr>
                <?php $_i = 0; ?>
                <?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
                <?php /** @var $_item \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($block->getItems() as $_item): ?>
                    <?php if ($_i++ == 0): ?>
                        <th scope="row" class="cell product"><span><?php /* @escapeNotVerified */
                                echo __('Product') ?></span></th>
                    <?php endif; ?>


                    <td data-th="<?php echo $block->escapeHtml(__('Product')); ?>"
                        class="cell product info products-grid">
                        <div class="item">
                            <div class="item-inner">
                                <div class="box-image">
                                    <a class="product-item-photo" href="<?php /* @escapeNotVerified */
                                    echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */
                                    echo $block->stripTags($_item->getName(), null, true) ?>">
                                        <?php echo $block->getImage($_item, 'product_comparison_list')->toHtml(); ?>
                                    </a>


                                </div>
                                <div class="box-info">
                                    <h2 class="product name product-item-name product-name">
                                        <a href="<?php /* @escapeNotVerified */
                                        echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */
                                        echo $block->stripTags($_item->getName(), null, true) ?>">
                                            <?php /* @escapeNotVerified */
                                            echo $_helper->productAttribute($_item, $_item->getName(), 'name') ?>
                                        </a>
                                    </h2>

                                    <?php /* @escapeNotVerified */
                                    echo $block->getProductPrice($_item, '-compare-list-top') ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, 'short') ?>

                                    <div class="bottom-action">
                                        <?php if ($_item->isSaleable()): ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                            echo $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($_item); ?>"
                                                  method="post">
                                                <?php echo $block->getBlockHtml('formkey') ?>
                                                <button type="submit" class="action tocart btn-action btn-cart">
														<span><?php /* @escapeNotVerified */
                                                            echo __('Add to Cart'); ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_item->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */
                                                        echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                        echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>

                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                            <a href="#" data-post='<?php /* @escapeNotVerified */
                                            echo $block->getAddToWishlistParams($_item); ?>'
                                               class="action towishlist btn-action link-wishlist"
                                               data-action="add-to-wishlist">
													<span><?php /* @escapeNotVerified */
                                                        echo __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                <?php endforeach; ?>
            </tr>
            </tbody>
            <tbody>
            <?php foreach ($block->getAttributes() as $_attribute): ?>
                <tr data-attribute-code="<?= $_attribute->getAttributeCode() ?>">
                    <?php $_i = 0 ?>
                    <?php foreach ($block->getItems() as $_item): ?>
                        <?php if ($_i++ == 0): ?>
                            <th scope="row" class="cell">
                                    <span class="attribute">
                                        <?php echo $block->escapeHtml($_attribute->getStoreLabel() ? $_attribute->getStoreLabel() : __($_attribute->getFrontendLabel())) ?>
                                    </span>
                            </th>
                        <?php endif; ?>


                        <td class="cell product attribute">
                            <div class="attibute value">
                                <?php switch ($_attribute->getAttributeCode()) {
                                    case "price": ?>
                                        <?php
                                        /* @escapeNotVerified */
                                        echo $block->getProductPrice(
                                            $_item,
                                            '-compare-list-' . $_attribute->getCode()
                                        )
                                        ?>
                                        <?php break;
                                    case "small_image": ?>
                                        <?php $block->getImage($_item, 'product_small_image')->toHtml(); ?>
                                        <?php break;
                                    case "description": ?>
                                        <div class="compare-description-value" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false}}'>
                                            <div data-role="collapsible">
                                                <div data-role="trigger">
                                                    <span><?= __('Description'); ?></span>
                                                    <i class="fa fa-chevron-up"></i>
                                                    <i class="fa fa-chevron-down"></i>
                                                </div>
                                            </div>
                                            <div data-role="content">
                                                <?php /* @escapeNotVerified */
                                                echo $_helper->productAttribute($_item, $block->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?>
                                            </div>
                                        </div>
                                        <?php break;
                                    default: ?>
                                        <?php /* @escapeNotVerified */
                                        echo $_helper->productAttribute($_item, $block->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?>
                                        <?php break;
                                } ?>
                            </div>
                        </td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form]": {
                    "catalogAddToCart": {}
                }
            }
            
        
        </script>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('You have no items to compare.') ?></div>
    </div>
<?php endif; ?>
