<?php
$_dtmHelper = $this->helper('Datacom\LgkStore\Helper\Data');
?>
<meta name="facebook-domain-verification" content="t4jw4x60e3hc6crq5klrqrjdyf5x6l" /> 
<link rel="preload" as="style" href="<?= $block->getViewFileUrl('fonts/Blank-Theme-Icons/Blank-Theme-Icons.woff2'); ?>">
<!-- Global site tag (gtag.js) - Google Ads: 388797009 -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-388797009"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  //gtag('config', 'AW-388797009');
  gtag('config', 'AW-388797009', {'allow_enhanced_conversions':true});
</script>
<!-- Facebook Pixel Code -->
<!-- <script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '294341321923363');
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=294341321923363&ev=PageView&noscript=1"
/></noscript> -->
<!-- End Facebook Pixel Code -->
<!-- Hotjar Tracking Code for https://www.kartandgo.store/ -->
  <script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2038055,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
<meta name="google-site-verification" content="Oq6sddCz_m0EIRX3k9a22TPzRp9-6fR3JMym9z2fs-Q" />
<!-- TrustBox script -->
<script type="text/javascript" src="//widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js" async></script>
<!-- End TrustBox script -->
<script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "9bs0ndtkh7");
</script>
<style type="text/css">
  html[lang="en"] .hidden-en,
  html[lang="it"] .hidden-it,
  html[lang="fr"] .hidden-fr,
  html[lang="de"] .hidden-de {
    display: none !important;
  }
</style>
<?php if ($_dtmHelper->getStoreId() == 20): ?>
  <script type="text/javascript">
    require(
      ['jquery'],
      function($) {
        $('h1.page-title span').each(function() {
          if ($(this).html() == 'My Account') {
            $(this).html('Il mio Account');
          }
        });
        $('.nav.items .nav.item').each(function() {
          if ($(this).html() == 'My Account') {
            $(this).html('Il mio Account');
            return;
          }
          if ($(this).html() == '<strong>My Account</strong>') {
            $(this).html('<strong>Il mio Account</strong>');
            return;
          }
        });
        $('.customer-menu > ul > li:first-child a').each(function() {
          if ($(this).html() == 'My Account') {
            $(this).html('Il mio Account');
          }
        });
      }
    );
  </script>
<?php endif; ?>