<?php /*
<?php /* @var $block \Trustpilot\Reviews\Block\Success *//* ?>     
<?php
    $orderJsonOutput = $block->getOrder();
    $orderData = json_decode($orderJsonOutput, true);
?>
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
        tp('createInvitation',<?php echo $orderJsonOutput; ?>);
    });
</script>
<?php if (array_key_exists('recipientEmail', $orderData)): ?>
    <p>E-mail cliente: <span id="success-order-mail"><?php echo $orderData['recipientEmail']; ?></span></p>
<?php endif; ?>

*/ ?>