<?php /* @var $block \Trustpilot\Reviews\Block\Success */?>     
<?php
    $orderJsonOutput = $block->getOrder();
    $orderData = json_decode($orderJsonOutput, true);
?>
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
        tp('createInvitation',<?php echo $orderJsonOutput; ?>);
    });
    <?php if (array_key_exists('recipientEmail', $orderData)): ?>
    var mailClienteOrdine = '<?php echo $orderData['recipientEmail']; ?>';
    <?php endif; ?>
</script>