<?php

//tag_handling=html!!!!!!!!!!!!!!!!

require '000.deepl_data.php';

$cwd = dirname(__FILE__);

$magentoRoot = dirname(dirname($cwd));

$dbData = require($magentoRoot.'/app/etc/env.php');
$dbData = $dbData['db']['connection']['default'];

if (!function_exists('get_connection')) {
	function get_connection($dbData) {
		static $conn = null;
		
		if (is_null($conn)) {
			$conn = new \mysqli($dbData['host'], $dbData['username'], $dbData['password'], $dbData['dbname']);
		}
		
		if ($conn->connect_error) {
			throw new \Exception('Connection failed: ' . $conn->connect_error);
		}
		
		return $conn;
	}
}

$conn = get_connection($dbData);
$conn->set_charset('utf8');

//Recupero i valori dell'attributo manufacturer
$glossarioMarche = [];
$results = $conn->query('SELECT ov.value FROM eav_attribute_option_value ov
INNER JOIN eav_attribute_option o ON o.option_id=ov.option_id
INNER JOIN eav_attribute a ON a.attribute_id=o.attribute_id
WHERE a.attribute_code=\'manufacturer\'
GROUP BY ov.value;');
if (!$results) {
    throw new \Exception('Query error: '.$conn->error);
}
while ($row = $results->fetch_assoc()) {
    $urlEncoded = urlencode($row['value']);
    $glossarioMarche[] = sprintf("%s\t%s", $urlEncoded, $urlEncoded);
}

if (empty($glossarioMarche)) return;

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

$postFields = "name=Glossary1&target_lang=".$deeplTargetLang."&source_lang=IT&entries=".implode("\n", $glossarioMarche)."&entries_format=tsv";
echo $postFields."\r\n";
curl_setopt($ch, CURLOPT_URL, $deeplDomain.'/v2/glossaries');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $postFields);

$headers = array();
$headers[] = sprintf('Authorization: DeepL-Auth-Key %s', $deeplAuthKey);
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch)."\r\n";
    return;
}

curl_close($ch);

$deeplData = json_decode($result, true);

if (!array_key_exists('glossary_id', $deeplData)) {
    echo "ERRORE, RISPOSTA: \r\n".$result."\r\n";
    return;
}

file_put_contents(dirname(__FILE__).'/'.$deeplData['glossary_id'].'.json', $result."\r\n", FILE_APPEND);

echo "Operazione completata, glossario: ".$deeplData['glossary_id']."\r\n";