<?php

require 'deepl_data.php';

$cwd = dirname(__FILE__);

$magentoRoot = dirname(dirname($cwd));

$dbData = require($magentoRoot.'/app/etc/env.php');
$dbData = $dbData['db']['connection']['default'];

if (!function_exists('get_connection')) {
	function get_connection($dbData) {
		static $conn = null;
		
		if (is_null($conn)) {
			$conn = new \mysqli($dbData['host'], $dbData['username'], $dbData['password'], $dbData['dbname']);
		}
		
		if ($conn->connect_error) {
			throw new \Exception('Connection failed: ' . $conn->connect_error);
		}
		
		return $conn;
	}
}

$conn = get_connection($dbData);
$conn->set_charset('utf8');

$idAttributo = 122;  //url_key

//Recupero gli articoli che hanno già un valore sullo store francese per l'attributo interessato
$idProdottiValorizzati = [];
$results = $conn->query(sprintf('SELECT entity_id FROM catalog_product_entity_varchar
WHERE attribute_id=%d AND store_id=%d', $idAttributo, $idTargetStore));
if (!$results) {
    throw new \Exception('Query error: '.$conn->error);
}
while ($row = $results->fetch_assoc()) {
    $idProdottiValorizzati[] = $row['entity_id'];
}
if (empty($idProdottiValorizzati)) {
    $idProdottiValorizzati[] = -1;
}

$textData = [];
$results = $conn->query(sprintf('SELECT entity_id, value FROM catalog_product_entity_varchar
WHERE attribute_id=%d AND store_id=0 AND entity_id NOT IN (%s)', $idAttributo, implode(', ', $idProdottiValorizzati)));
if (!$results) {
    throw new \Exception('Query error: '.$conn->error);
}
while ($row = $results->fetch_assoc()) {
    $textData[$row['entity_id']] = $row['value'];
}

foreach ($textData as $entityId => $value) {
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $deeplDomain.'/v2/translate');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "text=".rawurlencode($value)."&target_lang=".$deeplTargetLang."&source_lang=IT");

    $headers = array();
    $headers[] = sprintf('Authorization: DeepL-Auth-Key %s', $deeplAuthKey);
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch)."\r\n";
        break;
    }
    curl_close($ch);

    $deeplData = json_decode($result, true);

    if (!array_key_exists('translations', $deeplData)) {
        if (array_key_exists('message', $deeplData)) {
            echo $deeplData['message']."\r\n";
        }
        break;
    }

    foreach ($deeplData['translations'] as $index => $data) {
        if (!array_key_exists('text', $data)) continue;

        $newValue = $data['text'];
    
        $stmnt = $conn->prepare('INSERT INTO catalog_product_entity_varchar (attribute_id, store_id, entity_id, value) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE value=?');
        $stmnt->bind_param('iiiss', $idAttributo, $idTargetStore, $entityId, $newValue, $newValue);
        $stmnt->execute();

        echo $entityId." aggiornato\r\n";
    }
}